### ISSUE TITLE
update power select dependency to resolve babel compilation issue

### ISSUE THREAD

**Issue by jonathannewman** [cibernox/ember-power-select-with-create#129]
We are seeing this error when trying to update dependencies in an Ember 3.28 application:  

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @embroider/macros]) in @embroider/macros/runtime.js

@embroider/macros/runtime.js: @babel/template placeholder "LOG_VIEW_LOOKUPS": Expected string substitution
```
This results from an older version of `@embroider/utils` being included by the 4.x `ember-power-select`.  The recent update to 5.0.4 of ember power select resolved that issue for `ember-power-select`,  but this package still causes that issue.  Is it possible to update that dependency?

**Comment by jonathannewman** [comment]
I can put together a PR to update this if that would be helpful.

**Comment by mcfiredrill** [comment]
Having the same issue, can we merge and release https://github.com/cibernox/ember-power-select-with-create/pull/130

**Comment by RosarioAleCali** [comment]
@cibernox Would it be possible to merge the PR and release a new version please? Thank you!

**Comment by RosarioAleCali** [comment]
It looks like development has been slowing down a bit, @cibernox. Would it be possible to move this addon to the adopted-ember-addons repo?

**Comment by mkszepp** [comment]
We have released v3. Its now a v2 addon and it works with eps v8. For older eps version please use v2 of this addon
