### ISSUE TITLE
Create option at bottom

### ISSUE THREAD

**Issue by vladstanca** [cibernox/ember-power-select-with-create#13]
I think the Add option should be the last option, or there should be a setting to have it as the last option. It seems more intuitive to start typing and then hit enter once the first option is what you are looking for. Currently, you have to use the mouse or arrow keys to move past the Add option.

**Comment by Ramblurr** [comment]
I agree, plus it would be nice to choose when to show or hide the suggestion option. If an option already exists that equals the suggestion term (for some definition of equal), then it shouldn't be displayed.

**Comment by PratheepV** [comment]
@vladstanca , please check the #37 .

**Comment by felixkiss** [comment]
Closed by #37
