### ISSUE TITLE
Expose API to user to hide create option

### ISSUE THREAD

**Issue by felixkiss** [cibernox/ember-power-select-with-create#17]
Suggested by @Ramblurr. Moved into its own issue from https://github.com/cibernox/ember-power-select-with-create/issues/13#issuecomment-208881405

I think we could expose an action that does this. E.g.

```hbs
{{#power-select-with-create
    options=countries
    searchField="name"
    selected=selectedCountry
    oncreate=(action "createCountry")
    showCreateOption=(action "hideCreateOptionOnSameName") as |country|
}}
  {{country.name}}
{{/power-select-with-create}}
```

```js
actions: {
  hideCreateOptionOnSameName(term) {
    let existingOption = this.get('countries').findBy('name', term);
    return !existingOption;
  },
},
```

@cibernox What do you think? Does this stay true to the style of other ember-power-select customizations?

**Comment by cibernox** [comment]
The idea looks reasonable. The name of the options is not very concise, but I can't come up with anything clearly better. `showCreateWhen=...`?

Another question would be, should the component has any "opinion" about what the proper behaviour is?

By example, if we decide the the proper default behaviour is to not allow to create an option when the search term matches **exactly** the name of any of the options (using the `searchField` in the `findBy` if the options are not just plain strings), and only do something different if the user passes an options.

In any case, it ok to start without a default behaviour and add it later, so :+1:
