### ISSUE TITLE
Async Search with Ember Data

### ISSUE THREAD

**Issue by thermokarst** [cibernox/ember-power-select-with-create#22]
I am using Ember 2.4.3, Ember Data 2.5.2, `ember-power-select-with-create` 0.1.8, and `ember-power-select` 0.10.0-beta.6.

I cannot get the async search to work correctly with `ember-power-select-with-create`. To clarify, async search seems to work just fine when using vanilla `ember-power-select`. I have reviewed issues #12 and #6, and PR #18.

Following is a MWE:

I have a search action that looks like this:
```javascript
searchTags(term) {
  return this.store.query('tags', { name: term });
},
```

a create action like this:
```javascript
newTag(term) {
  let tag = this.store.createRecord('tag', { name: term });
  tag.save();
},
```

and the template:
```hbs
{{#power-select-with-create
  search=(action "searchTags")
  selected=tag
  onchange=(action (mut tag))
  oncreate=(action "newTag")
  as |tag|
}}
  {{tag.name}}
{{/power-select-with-create}}
```

My ED query is firing off a network request, so I can confirm that that is working (and, returning an appropriate payload, which is populating in the store just fine). I checked out the source for `ember-power-select-with-create` and found that my calls aren't advancing past [this line](https://github.com/cibernox/ember-power-select-with-create/blob/master/addon/components/power-select-with-create.js#L48). Debugging the result payload at that point, it looks like the `buildSuggestionLabel` result is being appended to the ED results, but nothing seems to advance from there. No warnings in the console, no obvious issues. The net result is that the  `ember-power-select-with-create` widget continues to indicate that it is still loading ("Loading options...").

Any thoughts would be greatly appreciated! Also, I am more than happy to prepare a PR, if someone can lead me down the right path.
Thanks!

**Comment by felixkiss** [comment]
Thanks for reporting this issue. There is indeed an issue with ED. I am currently working on this. Fix will be out soon!

**Comment by felixkiss** [comment]
This should be addressed by #23. Can you test and confirm it working for you?

**Comment by thermokarst** [comment]
Tested: looks great to me. Thank you so much for such a crazy fast turnaround on that!

**Comment by zethussuen** [comment]
👍
