### ISSUE TITLE
Update to EPS 1.0.0-alpha

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select-with-create#26]

**Comment by felixkiss** [comment]
I will look into it. Should we also release a 1.0.0-alpha version?

**Comment by cibernox** [comment]
I doesn't necessarily has to be 1.0.0, that depends on if the api if this component is estable, but probably should respect the _alpha/beta_ surname, since EPS itself might iterate a little bit.

**Comment by felixkiss** [comment]
Outdated issue, since we are way past EPS 1.0.0
