### ISSUE TITLE
"render-double-modify" deprecation warning can be triggered by typing after clicking

### ISSUE THREAD

**Issue by mdentremont** [cibernox/ember-power-select-with-create#32]
When triggering the power-select-multiple open when input is entered, only do so in the "afterRender" queue to avoid the "render-double-modify" deprecation warning

Here are some steps to reproduce (with some of my guesses as to why this is occurring):

- Use a power-select-multiple which asynchronously searches (ie: via ajax calls)
- Click on the input field to show results
- Click one of the dropdown results, and at the same time hit a character on your keyboard
- This should simultaneously:
 - Select the clicked option, which will cause the dropdown to close, and the options to be refreshed
 - Trigger the dropdown to re-open, due to the keyboard input

I created a sample repo [here](https://github.com/mdentremont/reproduce-double-render) which demonstrates the issue - load up the "page" route to try it out.

Here is the warning output:
```
DEPRECATION: You modified (-join-classes (-normalize-class "concatenatedTriggerClasses" concatenatedTriggerClasses) "ember-view" "ember-basic-dropdown-trigger" (-normalize-class "inPlaceClass" inPlaceClass activeClass=undefined inactiveClass=undefined) (-normalize-class "hPositionClass" hPositionClass activeClass=undefined inactiveClass=undefined) (-normalize-class "vPositionClass" vPositionClass activeClass=undefined inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
```

**Comment by mdentremont** [comment]
@cibernox I've found one change which gets rid of the deprecation warning (but it's not something we would want to do):

```diff
diff --git a/addon/templates/components/power-select-with-create.hbs b/addon/templates/components/power-select-with-create.hbs
index 71465f6..2e807d0 100644
--- a/addon/templates/components/power-select-with-create.hbs
+++ b/addon/templates/components/power-select-with-create.hbs
@@ -44,6 +44,6 @@
   {{#if option.__isSuggestion__}}
     {{option.text}}
   {{else}}
-    {{yield option term}}
+    {{option}} {{term}}
   {{/if}}
 {{/component}}

```

**Comment by mdentremont** [comment]
@cibernox: Figured out the cause now and I can reproduce this with `power-select-multiple` as well.

The issue is no longer reproducible if I switch the `{{#component powerSelectComponentName` to  just `{{#power-select-multiple`. It must be an issue in Ember?

**Comment by cibernox** [comment]
@mdentremont Perhaps. Either way, I think that this addon should, like EPS itself, expose two different component, one for multiple and another for single mode, instead of accepting a `multiple=true` option.

**Comment by mdentremont** [comment]
@cibernox That would get rid of this issue :)

**Comment by mdentremont** [comment]
@cibernox: Here is a quick fix for the issue.. https://github.com/cibernox/ember-power-select-with-create/pull/33
