### ISSUE TITLE
doc for multiple select

### ISSUE THREAD

**Issue by bambery** [cibernox/ember-power-select-with-create#35]
The doc currently says to check the power select docs for options, but ember-power-select has a different helper for multiple selects, and does not pass an option. For power-select-with-create, you have to pass multiple=true - I found this out by searching through the issues on this repo. Can the doc please be updated? Also, are there any other options which aren't standard in power-select?

**Comment by cibernox** [comment]
I'd like to migrate this component to stop having the `multiple=true` option and provide two different components too, but I haven't had time. But apart from that, the options should be equivalent.

**Comment by bambery** [comment]
Just a line in the doc for how to set multiple would be excellent then. Is there any blocker to making the second component other than time? I can take a look at doing it later in the week.

**Comment by cibernox** [comment]
Not really, should be pretty straightforward.
