### ISSUE TITLE
Debouncing search with ember concurrency doesn't work

### ISSUE THREAD

**Issue by musaffa** [cibernox/ember-power-select-with-create#42]
In `ember-power-select`, debouncing with ember runloop and ember-concurrency works as shown in the Cookbook [examples](http://www.ember-power-select.com/cookbook/debounce-searches). But with this addon, only runloop debounce works. Debouncing with `ember-concurrency` doesn't work.

**Comment by kernel-io** [comment]
this should be closed as it does work, you just need to make sure what you are returning from your task doesn't error out (i.e: an ember data query that returns a 404 or something )

**Comment by john-griffin** [comment]
@cibernox I don't believe this should have been closed. Taking a basic working debounced with ember-concurrency power-select and moving it over to power-select-with-create does not work. Perhaps it has something to do with how the search action is resolved? https://github.com/cibernox/ember-power-select-with-create/blob/master/addon/components/power-select-with-create.js#L57
