### ISSUE TITLE
Doesn't install ember-power-select

### ISSUE THREAD

**Issue by dustinfarris** [cibernox/ember-power-select-with-create#5]
Probably should move from devDependencies to dependencies in package.json

**Comment by cibernox** [comment]
Indeed

**Comment by cibernox** [comment]
As a side note, ember-power-select fixed some problems when being included both as a dependency of the app and as a dependency of a dependency very recently, so when I update I will also bump the dependency to 0.8.0-beta.X

**Comment by cibernox** [comment]
Fixed in version 0.1.4
