### ISSUE TITLE
TypeError: Cannot read property '__isSuggestion__' of null

### ISSUE THREAD

**Issue by abhilashlr** [cibernox/ember-power-select-with-create#60]
Happens when an ember-power-select-with-create has allowClear=true.

Please refer:
https://ember-twiddle.com/cd70ac43c2f408c18dce05d6b1575f16?openFiles=controllers.application.js%2C

This was working fine in 0.2.6. Updating to 0.4.1 caused this issue.

EPS Version: 1.7.0
EPS-with-create Version: 0.4.1

**Comment by cibernox** [comment]
This can be closed now
