### ISSUE TITLE
How to change "Add" message

### ISSUE THREAD

**Issue by hairetdin** [cibernox/ember-power-select-with-create#61]
In ember-power-select allow to change noMatchesMessage, searchMessage as options. What about option for "Add" message? I need it to translate to another languages . For example:

```
{{#power-select-with-create
  searchMessage=(t 'Type to search')
  noMatchesMessage=(t 'No results found') 
  loadingMessage=(t 'Loading options...')
  addMessage=?
 ...
```

**Comment by felixkiss** [comment]
You can customize it by passing an action to `buildSuggestion`. See [the docs](https://github.com/cibernox/ember-power-select-with-create#control-the-create-options-label---default-add-option)

**Comment by hairetdin** [comment]
I apologize, I did not read the documentation well. That's fine for me. The question is settled
