### ISSUE TITLE
where is the code of the example in the readme file.

### ISSUE THREAD

**Issue by NouranMahmoud** [cibernox/ember-power-select-with-create#66]
It will be useful for the documentation to share the code of this demo https://ember-power-select-with-create.pagefrontapp.com/ .. I've searched for it but I couldn't find it.

**Comment by cibernox** [comment]
Added to the description of the repo at the top. Good advise!

**Comment by NouranMahmoud** [comment]
I can see that you added the demo link not the *source code*.

**Comment by cibernox** [comment]
The source code has always been there. It's the dummy app: https://github.com/cibernox/ember-power-select-with-create/blob/master/tests/dummy/app/templates/application.hbs
