### ISSUE TITLE
Latest version breaks application tests

### ISSUE THREAD

**Issue by artursmirnov** [cibernox/ember-power-select-with-create#68]
Trying to update the addon to version 0.4.4 and application tests are flooded by messages like this one:
```
Could not find module `@ember/test` imported from `ember-power-select/test-support/helpers`
```
Looks like some other dependency has to be updated as well, but I'm not sure which one exactly. Could you please help to figure out?

Version 0.4.3 works fine.

**Comment by cibernox** [comment]
@artursmirnov Try 0.4.5

**Comment by artursmirnov** [comment]
@cibernox thanks for the quick response! 0.4.5 runs for me locally, but still fails on CI with the same error. Probably something is wrong with environment. I'll investigate further and post here. Thanks for help!

**Comment by cibernox** [comment]
@artursmirnov The reason must be some sort of cache. This version requires ember-cli-babel 6.6.0 or bigger.
