### ISSUE TITLE
Can we hide searchMessage?

### ISSUE THREAD

**Issue by dineshvgp** [cibernox/ember-power-select-with-create#72]
I feel, it is obvious that the user has to type something when they click dropdown. Can we not show the search message if the value is false?

`searchMessage=false`

Let me know if I can raise a PR for this?

**Comment by erikmellum** [comment]
Also curious about this. Any information?

**Comment by erikmellum** [comment]
Super easy. Just use ```.ember-power-select-option--search-message { display: none; }```

**Comment by cibernox** [comment]
Actually, I believe that if you pass `searchMessage=false` that should already be the behavior: https://github.com/cibernox/ember-power-select/blob/f329318ce514fb8923f035619c140ca37d5e117c/addon/components/power-select.js#L187-L192

**Comment by erikmellum** [comment]
Oh interesting! I tried using `searchMessage=''` and it didn't work. I didn't even try using `searchMessage=false` because this thread was unresolved and I assumed you couldn't. Thanks!

**Comment by cibernox** [comment]
I didn't even try, but I though that was the default behaviour. Afaik it has been that way for ages.

**Comment by erikmellum** [comment]
Maybe I just missed it in the documentation, but I don't think I saw that in there. At any rate now I know, thanks.
