### ISSUE TITLE
Save input when click outside of EPS

### ISSUE THREAD

**Issue by Techn1x** [cibernox/ember-power-select-with-create#85]
Currently using `power-select-multiple-with-create` component to allow a user to type in email addresses into a list & create them. We have found that sometimes the user forgets to press enter or click the "Add" button in EPS - then the last email address they entered disappears when they click away. Is there a way to save when the user clicks away from EPS instead of forgetting the entry?

**Comment by cibernox** [comment]
Not by default, but every sub-component of `ember-power-select` can be replaced by your own, so you could pass a custom `beforeOptions` component that knows how to remember the typed text, maybe using a service.

You can read about the subcomponents here: https://ember-power-select.com/docs/architecture

**Comment by Techn1x** [comment]
Thanks, I'll report back here when I have some working code

**Comment by Techn1x** [comment]
Had a bit of trouble trying a `beforeOptionsComponent`.. not a whole lot of help out there for this custom components feature...

I tried this, but it created a weird second input box & I wasn't quite sure what to do from there

```handlebars
{{#power-select-multiple-with-create
					options=reportModel.notify.email
					selected=reportModel.notify.email
					onchange=(action (mut reportModel.notify.email))
					oncreate=(action "createContactEmail" reportModel.notify.email)
					beforeOptionsComponent="test-eps-component"
					as |contact| }}
					{{contact}}
				{{/power-select-multiple-with-create}}
```

```javascript
//app/components/test-eps-component.js
import BeforeOptionsComponent from 'ember-power-select/components/power-select/before-options';
export default BeforeOptionsComponent.extend({
});
```

**Comment by Techn1x** [comment]
I ended up getting a working solution for the behaviour I was after by using the `onclose` action like so;

```handlebars
{{#power-select-multiple-with-create
  options=reportModel.notify.email
  selected=reportModel.notify.email
  onchange=(action (mut reportModel.notify.email))
  oncreate=(action "createContactEmail" reportModel.notify.email)
  onclose=(action "createContactEmailSilent" reportModel.notify.email)
  as |contact| }}
    {{contact}}
{{/power-select-multiple-with-create}}
```

```javascript
actions: {
  createContactEmailSilent(contacts, select, e) {
    // Silently validate email & add if valid
    // NOTE: This is called when user clicks away from EPS or when EPS closes itself due to new entry.

    // If EPS is open, and there is text entered, and it hasn't been added to the list already
    let entry = select.searchText;
    if(select.isOpen && !isEmpty(entry) && !contacts.includes(entry)) {
      // If entry is an email
      let validate = this.get('basicValidationService');
      let isEmail = validate.validateEmail(entry);
      if(isEmail) contacts.pushObject(entry);
    }
  },
}
```

Hope someone finds this useful.
