### ISSUE TITLE
doesn't work with ember-power-select 2.x

### ISSUE THREAD

**Issue by alexborovkov** [cibernox/ember-power-select-with-create#89]
Seems like this addon doesn't work with latest ember-power-select 2.x

I've got `Uncaught Error: Assertion Failed: {{power-select}} requires an `onchange` function` for power-select components

**Comment by cibernox** [comment]
This addon needs to be updated to work with 2.X indeed, but I'm a bit short of time lately.

**Comment by jelhan** [comment]
I guess we are talking here about `ember-power-select@^3.0.0`, isn't it? It's working fine for 2.x but hasn't been updated for 3.x yet.

**Comment by mkszepp** [comment]
Closing this issue as eps is v8
